export const Userdata = [
    {
      id: 1,
      name: "Dheeraj Patil",
      username: "rava",
      email: "patildheeraj56@gmail.com",
      job: "data-analyst",
      usergain: 1500,
    },
    {
      id: 2,
      name: "Jatin Mangela",
      username: "Jats",
      email: "jatinmanegela@gmail.com ",
      usergain: 500,
    },
    {
      id: 3,
      name: "Abhichandra Yadav",
      username: "abhi",
      email: "abhiyadav@gmail.com",
      usergain: 2010,
    },
    {
      id: 4,
      name: "Shivani Sawant",
      username: "shiv",
      email: "shivsawant.com",
      usergain: 1000,
    },
    {
      id: 5,
      name: "Shahbaz Shaik",
      username: "shab",
      email: "shabaaz@gmail.com",
      usergain: 2000,
    },
    {
      id: 6,
      name: "Akshay Nichal",
      username: "akki",
      email: "akki56@gmail.com",
      usergain: 3000,
    },
    {
      id: 7,
      name: "Pravin Chaurasiya",
      username: "pravin",
      email: "pravink@gmail.com",
      usergain: 2800,
    },
    {
      id: 8,
      name: "Yash Mohite",
      username: "yash",
      email: "mohiteYash@gmail.com",
      usergain: 3000,
    },
    {
      id: 9,
      name: "Danger Don",
      username: "rage",
      email: "dongander@gmail.com",
      usergain: 2230,
    },
    {
      id: 10,
      name: "MR. GOGO",
      username: "gogo",
      email: "gogo56@gmail.com",
      usergain: 3420,
    },
    {
      id: 11,
      name: "Nam Teja",
      username: "Mark",
      email: "markidharhai@gmail.com",
      usergain: 1240,
    },
    {
      id: 12,
      name: "Dr. Ghunghruwala",
      username: "ghunghru",
      email: "ghunghru56@gmail.com",
      usergain: 1240,
    },
    {
      id: 13,
      name: "Uday Bhai",
      username: "udya",
      email: "golikidharhai@gmail.com",
      usergain: 2230,
    },
    {
      id: 14,
      name: "Sardar khan",
      username: "sardar",
      email: "chabikidharhai@gmail.com",
      usergain: 2430,
    },
    {
      id: 15,
      name: "Faizal Khan",
      username: "faizu",
      email: "khekelung@gmail.com",
      usergain: 2120,
    },
  ];
  